apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-test-demo
  labels:
    app: prometheus-test-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-test-demo
  template:
    metadata:
      labels:
        app: prometheus-test-demo
    spec:
      containers:
      - name: prometheus-test-demo
        image: prometheus-test-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8998
          name: metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: SPRING_REDIS_HOST
          value: "redis-service"
        - name: SPRING_REDIS_PORT
          value: "6379" 