apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-test-demo-monitor
  labels:
    app: prometheus-test-demo
spec:
  selector:
    matchLabels:
      app: prometheus-test-demo
  endpoints:
  - port: metrics
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s 