apiVersion: v1
kind: Service
metadata:
  name: prometheus-test-demo-service
  labels:
    app: prometheus-test-demo
spec:
  selector:
    app: prometheus-test-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: metrics
    port: 8998
    targetPort: 8998
  type: ClusterIP 